### ISSUE TITLE
Where is the passphrase supposed to come from?

### ISSUE THREAD

**Issue by pcbHikeME** [lfalck/AzureFunctionsPGPDecrypt#1]
I appreciate your example here.  thanks
AFAIK you need the passphrase to decrypt the private key.  Am I missing something?

**Comment by lfalck** [comment]
Yes, if you are using a passphrase you would need to provide it when calling DecryptStreamAsync, in this example i don't have one so i am just passing null.

**Comment by pcbHikeME** [comment]
hmm. so you can use PGP without a passphrase ?  did not know that.  thanks
