### ISSUE TITLE
PGP decryption giving an exception

### ISSUE THREAD

**Issue by inzi25** [lfalck/AzureFunctionsPGPDecrypt#2]
I am getting following error. Any idea ?
 Exception while executing function: PGPDecrypt. BouncyCastle.Crypto: invalid header encountered.

**Comment by inzi25** [comment]
Actually for testing purpose, I am passing the encrypted message on body and private key on query param.

**Comment by lfalck** [comment]
I am not sure, what are you using to generate the key and encrypt the message? 

The key should be ASCII armored and you probably need to Base64 encode it to pass it as a query parameter.

There is a sample command line program in the [AzureFunctionsPGPEncrypt](https://github.com/lfalck/AzureFunctionsPGPEncrypt) repo you can use, the key generated by it works with this function.

**Comment by inzi25** [comment]
Hi,

Thanks for the reply. I have used your program (Console app) to generate the encrypted message and all the keys. Ok, you mean when I pass as query param... I have to decode ?

**Comment by lfalck** [comment]
If you use this function without modification you should pass a Key Vault Secret Identifier (e.g. https://vaultname.vault.azure.net/secrets/secretname/) as a query parameter called privatekeysecretid. The content of that secret should be the base64 encoded private key.

**Comment by inzi25** [comment]
Yes, I have used that function with some modification. because currently I am checking this on local host. If I pass as base64, then getting below exception at DecryptAsync function,
Secret key for message not found.

**Comment by inzi25** [comment]
Please note, using the same private key and encrypted message. I could able to decryption on console app that you have shared. But my objective , achieving this as "Stream" output.

**Comment by lfalck** [comment]
You can actually fetch secrets from Key Vault even when running locally, as long as you have logged in with Azure CLI.

Anyway, this is a version of the function which gets the base64 encoded private key from a query parameter called "privatekeybase64" instead of from Key Vault: https://gist.github.com/lfalck/ce6e775d9e171ba3096af5cbff269024

**Comment by inzi25** [comment]
Thanks brother. It's awesome !

**Comment by inzi25** [comment]
Ok. I will try Azure key vault on local host with CLI

**Comment by inzi25** [comment]
Thanks, It is worked well.

**Comment by CitronDev** [comment]
So I am experiencing a different issue, but I am trying to execute the same process... 

The error I am receiving is: **Exception while executing function: PGPDecrypt. PgpCore: Object reference not set to an instance of an object.**

I extracted the private key that is ASCII armored and put the Base64 encode value within the Azure Key Vault. After that, I passed the secret identifier as a query parameter called privatekeysecretid. 

Additionally, I put the encrypted message within the Body of the request as it was generated by the Encrypt function. Unfortunately, the process fails when trying to decrypt the data. Does anyone know what is causing this error message?

**Comment by CitronDev** [comment]
How do you extract the private key? Below are the steps I took to extract the private key.
1. Open Kleopatra 
2. Right click Certificate and then Export Secret Certificate
3. ASCII armor

Is this process correct?

**Comment by lfalck** [comment]
Did you use a passphrase? In that case you need to Base64 encode it, add it to Key Vault, and pass the identifier as a query parameter called passphrasesecretid.

**Comment by CitronDev** [comment]
Yes, I passed the passphrase as a query parameter and when debugging, the value of the passphrase is correct after Base64 decode. 

Also, I even tried your sample that you provided above and the execution still failed with the same error message. I passed in the base64 encode as a query parameter named privatekeybase64.  https://gist.github.com/lfalck/ce6e775d9e171ba3096af5cbff269024

The point of failure is from FunctionExecutor.cs from the Microsoft.Azure.WebJobs.Host.Executors namespace.

**Comment by lfalck** [comment]
> Yes, I passed the passphrase as a query parameter and when debugging, the value of the passphrase is correct after Base64 decode.

You mean the Key Vault identifier, right? It looks something like this: https://vaultname.vault.azure.net/secrets/secretname/version

> Also, I even tried your sample that you provided above and the execution still failed with the same error message. I passed in the base64 encode as a query parameter named privatekeybase64. 

The version in the Gist does not support passing a passphrase, so unless you used an empty passphrase it won't work without modification.
