### ISSUE TITLE
OpenPGP keys

### ISSUE THREAD

**Issue by inzi25** [lfalck/AzureFunctionsPGPDecrypt#3]
Hi,

Hope you are fine. Need a small favor, Any idea how can we generate PGP keys with below requirements.
•	ASCII-armored text format (.asc)
•	formatted as OpenPGP (version 4)
•	key size of 1024-3072 bit, 2048 recommended
•	use the DH-DSS/DSA option with an encryption algorithm selected (typically Elgamal) or RSA type 1 (sign and encrypt)
•	be self-signed
•	set to never expire

**Comment by inzi25** [comment]
I have used below link and testing
https://smartninja-pgp.appspot.com/

**Comment by lfalck** [comment]
Hi!

If you are on Windows you kan use [Gpg4win](https://www.gpg4win.org/) to generate keys.
