### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by knaidoo33** [lfalck/AzureFunctionsPGPDecrypt#4]
Hello, 

This package has been very helpful - I do have one question. 

The package is running well, however the output files I am seeing isn't the same output I see when decrypting the files manually using Kleopatra. I am thinking this may be because the files are of type .csv.gz.gpg

Do you have any thoughts on how to handle this? My goal is to eventually be able to trigger this function from a data factory pipeline and write the data to a database. 

![image](https://user-images.githubusercontent.com/57462633/68438870-1943e180-0172-11ea-80dd-66bc88438788.png)

Thank you.
K

**Comment by lfalck** [comment]
Hi!

If the file was gzipped before it was encrypted i guess you need to unzip the output?

**Comment by knaidoo33** [comment]
got it working! thanks! 
Have you had any luck triggering Azure functions from Data Factory? I am trying to figure out how to pass data into the body from there.

**Comment by lfalck** [comment]
Maybe push the data to blob storage with Data Factory and use a blob triggered function to decrypt and write to the database?
