### ISSUE TITLE
Error while running this function in my Azure account.

### ISSUE THREAD

**Issue by login21** [lfalck/AzureFunctionsPGPDecrypt#6]
Hi ,

I am trying to use this function to decrypt my files but getting this error "Object reference not set to an instance of an object."

At this line I am getting this error. 
`await pgp.DecryptStreamAsync(inputStream, outputStream, privateKeyStream, passPhrase);`

Just to verify my key and passphrase locally I used below and it is working. 
`pgp.DecryptFile(inputFileLocation, outputFile,privateKeyLocation, passPhrase); `

I am not sure what I am doing wrong here.

**Comment by lfalck** [comment]
Hi!

Hard to say what is wrong, are you sending the encrypted message in the http request body?

**Comment by login21** [comment]
I am reading decrypted file from Azure blob storage like below 

 ```
 BlobContainerClient container = new BlobContainerClient(connectionString, containerName);
                 BlobClient blob = container.GetBlobClient(blobName);
                 BlobDownloadInfo download = blob.Download();
    
               using(Stream inputStream = new MemoryStream())
                    {
                    download.Content.CopyTo(inputStream);
                    Console.Write($"input steram is ..., {inputStream.Length}");
```

and sending inputstream to 

`await DecryptAsync(inputStream, privateKey, passphrase);`

I checked the inputstream length and its not null.

**Comment by lfalck** [comment]
Maybe try resetting the position of inputStream after copying to it if you are not doing that? Hard to know without a complete example 🙂
`inputStream.Seek(0, SeekOrigin.Begin);`

**Comment by login21** [comment]
Thank you for your quick response. I tried this and now some other error. 

`Secret key for message not found.`

Is this possible that my blob content is getting tempered ?

I tried decrypting same blobfile after downloading to my laptop and its working fine.

`pgp.DecryptFile(inputFileLocation, outputFile,privateKeyLocation, passPhrase);`

Here is my full code.

```
using System;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Microsoft.Azure.KeyVault;
using PgpCore;
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System.Collections.Generic;

namespace pgpdecryption
{
    public static class PgP_Decryption
    {
        [FunctionName("PgP_Decryption")]
        public static async Task<IActionResult> RunAsync(
        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req, ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");

            string passphrase;
            string privateKey = null;

            try
            {
                //var passphrase =  Environment.GetEnvironmentVariable("Passphrase", EnvironmentVariableTarget.Process);
                passphrase = System.Environment.GetEnvironmentVariable("pgp-passsphrase");
                privateKey = System.Environment.GetEnvironmentVariable("Privatekey");
                //log.LogInformation($" *** passphrase is, {passphrase}");

                //log.LogInformation($" *** privateKey is, {privateKey}");

                if (passphrase == null || privateKey == null)
                {
                    return new BadRequestObjectResult("Not able to get the secrets from Vault.");
                }
                else
                {
                    string connectionString = "myconnection-string";
                    string inputContainerName = "input";
                    string blobName = "test.txt.pgp";

                    BlobContainerClient container = new BlobContainerClient(connectionString, inputContainerName);
                    BlobClient blob = container.GetBlobClient(blobName);
                    BlobDownloadInfo download = blob.Download();

                    using(Stream inputStream = new MemoryStream())
                    {
                    download.Content.CopyTo(inputStream);
                    inputStream.Seek(0, SeekOrigin.Begin);
              
                    Stream decryptedData = await DecryptAsync(inputStream, privateKey, passphrase);

                    StreamReader reader = new StreamReader(decryptedData);
                    log.LogInformation($"decrypted data reader ..., {reader}");
                    string text = reader.ReadToEnd();

                    return new OkObjectResult(text);

                    }
                       

                }

            }
            catch (Exception e)
            {
                log.LogInformation($"Error , {e.Message}");
                return new BadRequestObjectResult(e.Message);
            }

        }


        private static async Task<Stream> DecryptAsync(Stream inputStream, string privateKey, string passPhrase)
        {
            using (PGP pgp = new PGP())
            {
                Stream outputStream = new MemoryStream();

                using (inputStream)
                using (Stream privateKeyStream = GenerateStreamFromString(privateKey))
                {
                    await pgp.DecryptStreamAsync(inputStream, outputStream, privateKeyStream, passPhrase);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    return outputStream;
                }
            }
        }

        private static Stream GenerateStreamFromString(string s)
        {
            MemoryStream stream = new MemoryStream();
            StreamWriter writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }

    }
}
```

**Comment by login21** [comment]
Most probably it is something to do with Privatekey which i stored in Key Vault.

When I run the same code with below changes in my local it works.

```
string passphrase = "mypassphrase" ;

 using (StreamReader sr = new StreamReader("/Users/sangkumari/Sample/privatekeyfile.asc"))
                    {
                    String privateKey = sr.ReadToEnd();
                    Stream decryptedData = await DecryptAsync(inputStream, privateKey, passphrase);
}
```

**Comment by lfalck** [comment]
That code works for me, one thing i had to change was that in the original code the private key was base64 encoded. If your key in the environment variable is also base64 encoded you need to convert it before passing it along:
```
privateKey = System.Environment.GetEnvironmentVariable("Privatekey");
byte[] privateKeyBytes = Convert.FromBase64String(privateKey);
privateKey = Encoding.UTF8.GetString(privateKeyBytes);
```

**Comment by login21** [comment]
No I have encoded my keys. So I am not decoding them.

While creating my secret in Key Vault, I directly copied my private key file content there.

**Comment by lfalck** [comment]
But in the example above you are not using KeyVault, you are reading the private key from an Environment variable? If the content of that Environment variable ("Privatekey") is base64 encoded you need to decode it before passing it to DecryptAsync.

**Comment by login21** [comment]
I have created my Key valut secret like this

`az keyvault secret set --vault-name mySuperSecretVault -n pgp-passsphrase --value 'mypublic key'`

and then adding this to my Azure function "App Settings" and fetching it with environment variable. I verified this value by printing the content but not sure why its not working

![image](https://user-images.githubusercontent.com/17980162/84235306-fc70f180-ab38-11ea-87fc-dc7eea2c16a8.png)

**Comment by lfalck** [comment]
I see, you are using key vault references. 

--value 'mypublic key'
Public key is not the same as passphrase, passphrase is the password for the private key, is that what you are using?

**Comment by login21** [comment]
So here in my case "pgp-passphrase" is the passphrase and "Privatekey" is my private key and setting them as 

az keyvault secret set --vault-name mySuperSecretVault -n pgp-passsphrase --value '<mypassphrase>'

az keyvault secret set --vault-name mySuperSecretVault -n Privatekey --value '<mypublic key content>'

**Comment by lfalck** [comment]
OK that should work.

What does the private key you are using look like?

Is it multiple lines starting like this:
-----BEGIN PGP PRIVATE KEY BLOCK-----

Or is it just one line?

**Comment by login21** [comment]
Yes It is multiple lines starting with :

-----BEGIN PGP PRIVATE KEY BLOCK-----

**Comment by lfalck** [comment]
I had issues getting multiple lines to work in KeyVault. Maybe try base64 encoding the key before adding it? Then you will need to decode it in the program as i wrote about above.

**Comment by login21** [comment]
Yes it worked after base64 encoding . Thank you so much for your quick response and help. :)
